### ISSUE TITLE
Quantity of num_token encountered by LocalViT on DeiT

### ISSUE THREAD

**Issue by whiteBAI-97** [ofsoundof/LocalViT#5]
When I used LocalViT on DeiT, I found that when the teacher model of distillation learning is not added, numtoken = 197 needs to be disassembled into class_token = 1 and image_token = 196. However, after adding the teacher model, I found numtoken = 198. The extra token is distillation token? I don't know how to split the extra distillation token. I hope the author can give me some ideas. Thank you very much.

**Comment by whiteBAI-97** [comment]
I use the following two methods to split the distil token. Both of them can run, but I'm not sure whether the location of the distil token is in front of or behind imagetoken. Thank the author for his comments:
Scheme I:
cls_token, dist_token, x_imtoken = torch.split(x, [1, 1, num_token - 2], dim=1)

Scheme II:
cls_token, x_imtoken, dist_token = torch.split(x, [1, num_token - 2, 1], dim=1)

**Comment by ofsoundof** [comment]
Hi @whiteBAI-97 , 

You are right that the additional token is the distillation token. You can split the teacher token and distillation token according to how they are concatenated.

[https://github.com/ofsoundof/LocalViT/blob/main/models/deit.py#L46
](url)

And in your case, it should be `torch.split(x, [1, 1, 196], dim=1)`.
